### ISSUE TITLE
Document architecture (with a great diagram)

### ISSUE THREAD

**Issue by slifty** [BadIdeaFactory/contextubot#10]
During some of the planning sessions we plotted out high level architecture, that should be digitized and reflected in our repository.

**Comment by Laurian** [comment]
![exhibit 1](https://user-images.githubusercontent.com/21679/29630132-d07f16c6-8843-11e7-95fb-a43d404e20dc.png)
![exhibit 2](https://user-images.githubusercontent.com/21679/29630142-d6fc3100-8843-11e7-8fd8-cda271487900.png)
![exhibit 3](https://user-images.githubusercontent.com/21679/29630149-decdd956-8843-11e7-9e67-2f531e8ced61.png)

**Comment by slifty** [comment]
That last one in particular is key

**Comment by slifty** [comment]
The following was written by @Laurian over Slack and will need to be incorporated in whatever gets made out here:

Basically, there is:

A. a front-end, that connects to:
B. an API, that instruments:
C. a metadata database and
D. a fingerprint database.


As basic AWS infrastructure:

A. will be static hosted: AWS S3 + AWS CloudFront
B. deployed as docker image on AWS Elastic Beanstalk + AWS CloudFront
C. TBD, depends on context.json features
D. deployed as worker docker instace on AWS Elastic Beanstalk + AWS Elastic File System (persistent, shareable volume)


As better AWS infrastructure (all these assume we're stuck with Audfprint):

A. same.
B. stateless AWS Lambda + API Gateway (AWS CloudFront)
C. same.
D. deployed as 2 different tasks on AWS ECS (Elastic Container Store = Docker), where:
D1. one single instance for the Audfprint db indexing, with R/W access to shared AWS EFS with
D2. autoscalable instances for Audfrint db queries, with RO access to db files
D3. small autscalable instances that generate fingerprint files out of media files, to be used in D1 for ingesting and indexing context provider's media, and in D2 for queries


The better one is an pre-emptive optimisation of the basic one, as Audfprint is filesystem bound and that's always a nightmare in the cloud.
Since we're not sure we'll stick with Audfprint yet (we might swap it with Dejavu which uses MySQL, which as scalability it is already solved), we should start with the basic one and evolve from there.


All the above are in the idea of supporting these 2 workflows:

I. Context provider pushes to contextubot for ingest media + metadata:

Imagine IA using our API to upload 1337 files of 1h each of CNN News, each file comes with additional JSON metadata (programme, etc).
Contextubot has to generate fingerprint files for each media file, and add those fingerprints to the master db. The metadata will be stored in the metadata db.

[Ideally IA would give us metadata and fingerprint files, that's a long discussion, WRT standardisation of fingerprints]

II. Some user of contextubot (via site, API, browser extension, etc.) sends a tweet with video to be contextualised.

Thats for us media and metadata, we will download that media, fingerprint it and query it against the DB. In the envetuality of multiple hits, we'll use the metadata around those hits to discriminate/sort/filter.


The magic of the project is mostly in the results filtering and presentation not in the above infrastructure mechanics; but those mechanics should allow us to easily deploy different parallel implementations from fron-end to even fingerprint implementations.

![image](https://user-images.githubusercontent.com/208884/29697264-17916522-891c-11e7-9f20-ad21d324cb22.png)

![image](https://user-images.githubusercontent.com/208884/29697269-1bb55906-891c-11e7-93e1-587b17e5a420.png)

**Comment by slifty** [comment]
I meant to reference this issue in a commit message, but, #18 is intended to provide a high level architecture for our discussion.  Lets talk tomorrow about it.
