### ISSUE TITLE
Add User Stories

### ISSUE THREAD

**Issue by maboa** [BadIdeaFactory/contextubot#13]
The point of User Stories is to articulate:

- Who are our stakeholders? (could be separate doc)
- What are the different user types? / How do we want to support them (eg. political wonk/ rabid partisan/ hot-takes social person who wants to turn things around) ?

Put on github docs.

**Comment by slifty** [comment]
User stories have been fleshed out at https://github.com/BadIdeaFactory/contextubot/wiki/User-Stories
