### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/contextubot#15]
We will have several repos, `BadIdeaFactory/glorious-contextubot-*` is too long, we'll go for `BadIdeaFactory/contextubot-*`.

I will rename this current repo from `glorious-contextubot` to `contextubot` and it will be always the main repo for this project, and its `/docs` folder will always be published via github pages.

**Comment by Laurian** [comment]
Repo renamed, `/docs` setup as github pages https://badideafactory.github.io/contextubot/ with full disallow robots.txt until we'll have some content.

**Comment by Laurian** [comment]
Note: `audfprint-docker` repo will not follow `contextubot-*` naming as it is independent of this project and might be used in other projects too.

**Comment by slifty** [comment]
I'll make sure this is captured in #8 at which point I'll close the issue.
