### ISSUE TITLE
Make reader for audfprint data

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/contextubot#16]
Start with https://github.com/chrisguttandin/audio-fingerprinting-file-reader

**Comment by slifty** [comment]
For clarity: what exactly do you mean by "reader" here?

**Comment by Laurian** [comment]
Something that can make sense of the binary db file audfprint and be able to store fingerprints in other db systems, etc.

**Comment by slifty** [comment]
I *believe* that the binary db file is just a pickled hash map -- you can see how audfprint works with these files here: https://github.com/dpwe/audfprint/blob/master/hash_table.py

**Comment by Laurian** [comment]
https://github.com/chrisguttandin/audio-fingerprinting-file-reader is supposed to read that in js in browser, not node because DataView object is not there…

**Comment by slifty** [comment]
@Laurian I know you have since significantly reworked the way hashes are stored and looked up; I assume this issue is now obsolete but wanted to check before closing.

**Comment by Laurian** [comment]
tested this, we do not need in the end fingerprint data in front-end
