### ISSUE TITLE
Research alternatives to audfprint

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/contextubot#17]
http://willdrevo.com/fingerprinting-and-audio-recognition-with-python/
https://musicbrainz.org/doc/Fingerprinting

https://github.com/worldveil/dejavu
https://acoustid.org/chromaprint
http://www.phash.org/
http://open-fp.sourceforge.net/
https://github.com/dkourtesis/musicuri

http://www.relatable.com/tech/trm.html
http://people.csail.mit.edu/sshum/talks/audio_fingerprinting_sls_24Oct2011.pdf
http://www.gracenote.com/assets/Rafii-Coover-Han-An-Audio-Fingerprinting-System-for-Live-Version-Identification-using-Image-Processing-Techniques-ICASSP-2014.pdf

**Comment by maboa** [comment]
We are using both audfprint and dejavu.

**Comment by slifty** [comment]
I believe that we're just using audfprint at this point, but with a SQL modification similar to the way dejavu works.  @Laurian can you clarify when you get a moment?
