### ISSUE TITLE
Setup front-end build

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/contextubot#20]
https://github.com/facebookincubator/create-react-app 
+
https://ant.design/docs/react/use-with-create-react-app

And Travis CI

**Comment by Laurian** [comment]
Small issue, will sleep on it:
https://github.com/timarney/react-app-rewired/issues/75

**Comment by Laurian** [comment]
Damn, I forked it, fixed it, PR it https://github.com/timarney/react-app-rewired/pull/76
But I cannot use my fork in package.json because it is a monorepo, cannot have a git dep with folders!!! See https://github.com/npm/npm/issues/2974

**Comment by slifty** [comment]
@maboa could you post a link here to the setup instructions (either a wiki page or an .md; doesn't have to be perfect, just as complete as we have so far), at which point I think we can close this issue.
