### ISSUE TITLE
Research AWS setup options

### ISSUE THREAD

**Issue by Laurian** [BadIdeaFactory/contextubot#6]
Basically, manual vs automated setup/teardown with tools like Terraform.

Since we'll set it up first on a different AWS account, having this setup/teardown automated could be practical and elegant.

**Comment by slifty** [comment]
@Laurian can you briefly describe what the final decision(s) ended up being here?

**Comment by Laurian** [comment]
no need to automate this completely, we automate with travis ci deployment for front-end, but docker build, push and elastic-beanstalk deploy are manual because quay.io was too slow in the end
